# Generated by Django 4.2.4 on 2023-08-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workexperiences_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiences',
            name='somethinghere',
        ),
        migrations.AddField(
            model_name='workexperiences',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
